FROM node:16-alpine3.15

RUN apk add --update --no-cache g++ make python2
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

ENV NODE_ENV development
ENV PATH="./node_modules/.bin:$PATH"

COPY . ./

CMD ["npm", "run", "dev-server"]
