# Generated by Django 3.2.8 on 2022-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirligig', '0002_auto_20201218_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.TextField(null=True),
        ),
    ]
