# Generated by Django 3.2.8 on 2022-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_auto_20201101_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
